prod_settings:
  omero_conn:
    server: localhost
    port: 4064
    username: root
    password: mysecretpassword
test_settings:
  omero_conn:
    server: demo.openmicroscopy.org
    port: 4064
    username: jhay
    password: cooCheegh4qu
