omero_conn:
  server: localhost
  port: 4064
  username: root
  password: mysecretpassword
java_bin_path: /usr/local/openjdk-8/bin/java
java_class_path: /home/jovyan/work/OMERO.server-5.4.10-ice36-b105/lib/server/*
ice_config: /home/jovyan/work/pyOmeroUpload/ice.config
